language: python
python:
  - "2.7"
  - "3.5"

# command to install dependencies
install: 
  -  source ci/install.sh
  -  pip install coveralls

# command to run tests
script: 
  python setup.py test

after_success:
  coveralls
