language: python
python:
  - "2.7"
#  - "3.4"

# command to install dependencies
install: 
  -  source ci/install.sh
  -  pip install coveralls
# command to run tests
script: 
  nosetests --with-coverage --cover-package=skchem

after_success:
  coveralls