package:
  name: scikit-chem
  version: 0.0.4

source:
  path: . 

build:
  number: 0
  script: $PYTHON setup.py install --single-version-externally-managed --record=/tmp/record.txt # [not-win] # [not-win] # [not-win] 
  script: "%PYTHON%" setup.py install # [win]
 
requirements:
  build:
    - python
    - setuptools
    - nose
    - pytest
    - scikit-learn
 
  run:
    - python
    - numpy
    - scikit-learn
    - rdkit
    - pandas

test:
  imports:
    - skchem
  requires:
    - nose
    - pytest

  commands:
    - nosetests


about:
  home: https://github.com/richlewis42/scikit-chem
  license: MIT
  summary: Scientific Python Stack compatible cheminformatics library, using RDKit
  
