package:
  name: scikit-chem
  version: 0.0.6

source:
  path: .

build:
  number: 0
  script: $PYTHON setup.py install --single-version-externally-managed --record=/tmp/record.txt # [not-win]
  script: "%PYTHON%" setup.py install # [win]

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scikit-learn
    - scipy
    - rdkit
    - pandas
    - fuel
    - progressbar2
    - pytest
    - matplotlib
    - ipywidgets

test:
  imports:
    - skchem

  requires:
    - nose
    - pytest
    - coverage
    - pytest-cov

  #commands:
  #  - py.test

about:
  home: https://github.com/richlewis42/scikit-chem
  license: MIT
  summary: Scientific Python Stack compatible cheminformatics library, using RDKit
